{% set version = "4.0.10.1" %}
{% set sha256 = "68c1b166501b0d8d7b76e3017fa7a35256b293e7f482401a06c6db96d1fee5d9" %}

package:
  name: gatk4
  version: '{{ version }}'

source:
  url: https://github.com/broadinstitute/gatk/releases/download/{{ version }}/gatk-{{ version }}.zip
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

requirements:
  host:
  run:
    - openjdk >=8,<9
    - python

test:
  commands:
    - gatk -h
    - gatk --list
    - gatk HaplotypeCaller --help

about:
  home: https://www.broadinstitute.org/gatk/
  license: BSD-3-Clause
  license_family: BSD
  summary: Genome Analysis Toolkit (GATK4)
  dev_url: https://github.com/broadinstitute/gatk
