{% set version = "2.1" %}
{% set sha256 = "ee998574c74d5176039eea35da8ab7f71d05c61e7a75421905d59a3336d301d7" %}

package:
  name: pygenometracks
  version: '{{ version }}'

source:
  url: https://github.com/deeptools/pyGenomeTracks/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: true  # [py3k]

requirements:
  host:
    - python
    - setuptools
    - numpy 1.13.*
    - matplotlib 2.1.*
    - intervaltree >=2.1.0
    - pybigwig >=0.3.4
    - pytest
    - configparser >=3.5.0  # [py2k]
    - future >=0.16.0
    - hicexplorer >=2.1.4
  run:
    - python
    - numpy 1.13.*
    - matplotlib 2.1.*
    - intervaltree >=2.1.0
    - pybigwig >=0.3.4
    - pytest
    - configparser >=3.5.0  # [py2k]
    - future >=0.16.0
    - hicexplorer >=2.1.4

test:
  imports:
    - pygenometracks

about:
  home: https://github.com/deeptools/pyGenomeTracks
  license: GPL-3.0
  license_family: GPL
  summary: Standalone program and library to plot beautiful genome browser tracks.

extra:
  recipe-maintainers: fidel.ramirez@gmail.com
