{% set version = "1.0a" %}
{% set sha256 = "7356615d9ad365d10f01dfca4fad456cfc238a106d635dda5a4a143386bbefa0" %}

package:
  name: smcounter2
  version: '{{ version }}'

source:
  url: https://github.com/qiaseq/qiaseq-smcounter-v2/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'
  patches:
    - run-import.patch
    - get_pvalue-input.patch

build:
  number: 0
  skip: true # [not py27]

requirements:
  host:
    - python
    - r-base
  build:
    - wget
  run:
    - python
    - r-base
    - r-plyr
    - scipy
    - openpyxl
    - pysam
    - statistics
    - bedtools

test:
  commands:
    - smCounter2 --help

about:
  home: https://github.com/qiaseq/qiaseq-smcounter-v2
  license: MIT
  license_family: MIT
  summary: 'smCounter2: an accurate low-frequency variant caller for targeted sequencing data with unique molecular identifiers'
