{% set version = "1.2.0" %}
{% set sha256 = "383f588f195ac646a7b66112bf63783b77fed9c42b6739f7675da0688e7ae1fb" %}

package:
  name: arvados-python-client
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/a/arvados-python-client/arvados-python-client-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: true # [not py27]

requirements:
  host:
    - python
    - setuptools
    - ciso8601 <=1.0.4,>=1.0.0
    - future
    - google-api-python-client <1.7,>=1.6.2
    - httplib2
    - oauth2client <2,>=1.4.6
    - pycurl <7.21.5,>=7.19.5.1
    - python-gflags
    - requests
    - rsa
    - urllib3 >1.12
    - ws4py <0.4,>=0.3.5
  run:
    - python
    - ciso8601 <=1.0.4,>=1.0.0
    - future
    - google-api-python-client <1.7,>=1.6.2
    - httplib2
    - oauth2client <2,>=1.4.6
    - pycurl <7.21.5,>=7.19.5.1
    - python-gflags
    - requests
    - rsa
    - urllib3 >1.12
    - ws4py <0.4,>=0.3.5

test:
  imports:
    - arvados

about:
  home: https://github.com/curoverse/arvados
  license: Apache License 2.0
  license_family: Apache
  summary: Python API for Arvados, an open source platform for managing and analyzing biomedical big data

extra:
  skip-lints:
    - uses_setuptools
