{% set version = "0.98.9" %}
{% set sha256 = "ceb876c4cc8c43b3dca5c0e7bf4acf33f3f7be5c3a5d0b4ecfaeb4ecf6106c30" %}

package:
  name: w4mclassfilter
  version: '{{ version }}'

source:
  url: https://github.com/HegemanLab/w4mclassfilter/releases/download/v{{ version }}/w4mclassfilter_{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  script:
    - $R CMD INSTALL --build .

requirements:
  build:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library(w4mclassfilter)"

about:
  home: https://github.com/HegemanLab/w4mclassfilter
  license: NOASSERTION
  summary: Filter Workflow4Metabolomics dataMatrix, sampleMetadata, and variableMetadata files by sample-class, imputing zero
    for NA values and eliminating zero-variance rows and columns from the data-matrix. MIT Licence allows redistribution.
