{% set version = "5.2.9.122" %}
{% set sha256 = "3edd036cb5906548f2698d8d22f59e9ddb0bca7c3d8415eb1aee01a5cc777d4a" %}

package:
  name: pisces
  version: '{{ version }}'

source:
  url: https://github.com/Illumina/Pisces/releases/download/v{{ version }}/Pisces_{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: false

requirements:
  build:
    - wget
  run:
    # Not yet in conda, needs an external dotnet install to work
    # - dotnet

test:
  commands:
    # needs an external dotnet install
    #- pisces -h
    #- pisces_vqr -h

about:
  home: https://github.com/Illumina/Pisces
  license: GPL-3.0
  license_family: GPL
  summary: Somatic and germline variant caller for amplicon data. Recommended caller for tumor-only workflows.
