{% set version = "1.3.2" %}
{% set sha256 = "24266a2c7ef6673e8619ad132e91f55f3c15c005b4a7682395a1d36d1c7ff038" %}

package:
  name: scanpy
  version: '{{ version }}'

source:
  url: https://github.com/theislab/scanpy/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: true # [not py36]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - seaborn
    - scikit-learn
    - statsmodels
    - numba
    - python-igraph
    - louvain
    - anndata >=0.6.10
    - matplotlib >=2.2
    - pandas >=0.21
    - scipy
    - h5py
    - pytables
    - networkx
    - natsort

test:
  imports:
    - scanpy

about:
  home: https://scanpy.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  summary: Single-Cell Analysis in Python. Scales to >1M cells.
  dev_url: https://github.com/theislab/scanpy

extra:
  identifiers:
    - doi:10.1186/s13059-017-1382-0
