{% set version = "2.2.1" %}
{% set sha256 = "b2f11fac0f950ddf6bfc1170a68c4c8a7dbb588d5046d42ae6191acc1f0bf547" %}

package:
  name: python-chado
  version: '{{ version }}'

source:
  url: https://files.pythonhosted.org/packages/56/d4/d2fc5dfa0ef39e01680033ca40c59934a409abe9320b8eb3f5830d42c86b/chado-{{
    version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 1

requirements:
  host:
    - python
    - setuptools
    - sqlalchemy
    - psycopg2
    - biopython
    - bcbiogff >=0.6.4
    - wrapt
    - click
    - pyyaml
  run:
    - python
    - sqlalchemy
    - psycopg2
    - biopython
    - bcbiogff >=0.6.4
    - wrapt
    - click
    - pyyaml
    - future

test:
  imports:
    - chado
    - chado.analysis
    - chado.export
    - chado.organism
    - chado.util
  commands:
    - chakin --help > /dev/null
    - chakin analysis --help > /dev/null

about:
  home: https://github.com/galaxy-genome-annotation/python-chado
  license: MIT
  license_family: MIT
  summary: Chado library

extra:
  container:
    # unicode problem with click
    extended-base: true
