{% set version = "2.4.0" %}
{% set sha256 = "86e8176b0f89cc86a10f5c3e60c34140d591e9e6c85f129ccbfa13ecb16a9af2" %}

package:
  name: openms
  version: '{{ version }}'

source:
  url: https://github.com/OpenMS/OpenMS/releases/download/Release{{ version }}/OpenMS-{{ version }}-src.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: true # [py3k]

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
  host:
    - glib
    - autoconf
    - automake
    - python
    - zlib
    - libtool
    - xerces-c
    - gsl
    - boost
    - eigen
    - glpk  >=4.60
    - bzip2
    - qt  <5
    - libsvm >=3.21
    - seqan-library ==1.4.2
    - coinmp
  run:
    - python
    - glib
    - zlib
    - xerces-c
    - gsl
    - boost
    - eigen
    - glpk  >=4.60
    - bzip2
    - qt  <5
    - libsvm >=3.21
    - coinmp

test:
  commands:
    - FileMerger --help

about:
  home: https://github.com/OpenMS/OpenMS
  license: NOASSERTION
  summary: OpenMS is an open-source software C++ library for LC-MS data management and analyses

extra:
  identifiers:
    - biotools:openms
    - doi:10.1007/978-1-60761-987-1_23
