{% set version = "1.4.1" %}
{% set sha256 = "dc898f0b9f6491a69521bef82306d950f16566e4d0d6b3809b11725f707ba133" %}

package:
  name: basic
  version: '{{ version }}'

source:
  url: https://github.com/akds/BASIC/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 1
  noarch: python

requirements:
  host:
    - python
  run:
    - python
    - bowtie2

test:
  commands:
    - BASIC.py -h
    - touch file.txt && BASIC.py -b $(which bowtie2) -SE file.txt -a && rm file.txt result.fasta

about:
  home: http://ttic.uchicago.edu/~aakhan/BASIC/
  license: MIT
  license_family: MIT
  summary: BASIC is a semi-de novo assembly method for assembling BCR and TCR genes  from single cell RNA-seq data.
  dev_url: https://github.com/akds/BASIC
