{% set version = "0.3.3" %}
{% set sha256 = "9e8ec79b9f47e2bcf17185e3c14b98039e137140a003400e3101f1cbeefc1162" %}

package:
  name: slamdunk
  version: '{{ version }}'

source:
  sha256: '{{ sha256 }}'
  url: https://github.com/t-neumann/slamdunk/archive/v{{ version }}.tar.gz

build:
  entry_points:
    - slamdunk=slamdunk.slamdunk:run
    - alleyoop=slamdunk.alleyoop:run
    - splash=slamdunk.splash:run
  number: 0
  skip: true # [py3k or osx]

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - wget
  host:
    - python
    - setuptools
    - joblib >=0.9.4
    - pybedtools >=0.6.4
    - intervaltree >=2.1.0
    - pandas >=0.13.1
    - biopython >=1.63
    - pysam >=0.8.3
    - cython >=0.20.1
    - zlib
    - openjdk
    - r-base
    - ncurses
    - zlib
    - bzip2
    - curl
    - xz
    - libdeflate
  run:
    - python
    - joblib >=0.9.4
    - pybedtools >=0.6.4
    - intervaltree >=2.1.0
    - pandas >=0.13.1
    - biopython >=1.63
    - pysam >=0.8.3
    - cython >=0.20.1
    - zlib
    - openjdk
    - r-base
    - ncurses
    - zlib
    - bzip2
    - curl
    - xz
    - libdeflate

test:
  imports:
    - slamdunk
    - slamdunk.contrib
    - slamdunk.dunks
    - slamdunk.plot
    - slamdunk.slamseq
    - slamdunk.test
    - slamdunk.utils
  commands:
    - slamdunk --help
    - alleyoop --help
    - splash --help

about:
  home: http://t-neumann.github.io/slamdunk
  license: AGPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: SlamDunk is a novel, fully automated software tool for automated, robust, scalable and reproducible SLAMseq data
    analysis.
  dev_url: https://github.com/t-neumann/slamdunk
