{% set version = "2.2.1" %}
{% set sha256 = "65d2ddd8a9e47276ed68680ce1ed046a3f4fc258d320a4ffa1c17e753610afee" %}

package:
  name: minvar
  version: '{{ version }}'

source:
  url: https://github.com/MaryamZaheri/MinVar/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 1
  # minvar written for python 3.x only, so skip py27
  skip: true # [py27]

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - bedtools
    - biopython
    - blast >=2.3
    - bwa
    - emboss
    - htslib
    - lofreq >=2.1.3.1
    - pandas
    - pandoc
    - python
    - samtools >=1.3
    - seqtk
    - setuptools_scm_git_archive
    - sierrapy

test:
  commands:
    # test a few subcommands
    - minvar -h
    - minvar -v | grep 2.2.1

about:
  licence_file: LICENCE.md
  home: https://git.io/minvar
  license: NOASSERTION
  summary: A tool to detect minority variants in HIV-1 and HCV populations
  dev_url: https://github.com/MaryamZaheri/MinVar
