{% set version = "0.32.0" %}
{% set sha256 = "f4f757ec63328e1c2312d956437ec6fb7774226c631e3aba48e233e0c8e6b8a7" %}

package:
  name: nextflow
  version: '{{ version }}'

source:
  url: https://www.nextflow.io/releases/v{{ version }}/nextflow
  sha256: '{{ sha256 }}'

build:
  number: 2
  noarch: generic

requirements:
  host:
    - openjdk >=8,<=10
    - coreutils
    - curl
  run:
    - openjdk >=8,<=10
    - coreutils
    - curl

test:
  commands:
    - nextflow -v

about:
  home: https://github.com/nextflow-io/nextflow
  license: GPL-3.0
  license_family: GPL
  summary: A DSL for data-driven computational pipelines http://nextflow.io
