{% set version = "0.9.8" %}
{% set sha256 = "af34016b763fbf7f05339be13c8002ec2fb164647389ff35de819412c3be6a24" %}

package:
  name: gseapy
  version: '{{ version }}'

source:
  url: https://files.pythonhosted.org/packages/6f/1c/ed8881ad80e7c1ff0e21a1ee73ea75b784524493ecd5e720323f619211c8/gseapy-{{
    version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  skip: true # [py27]
  entry_points:
    - gseapy = gseapy.__main__:main
  number: 1

requirements:
  host:
    - python
    - setuptools
    - numpy >=1.13.0
    - pandas >=0.16
    - matplotlib >=1.4.3
    - beautifulsoup4 >=4.4.1
    - requests
    - lxml
    - html5lib
  run:
    - python
    - numpy >=1.13.0
    - pandas >=0.16
    - matplotlib >=1.4.3
    - beautifulsoup4 >=4.4.1
    - requests
    - lxml
    - html5lib

test:
  imports:
    - gseapy
  commands:
    - gseapy --help

about:
  home: https://github.com/zqfang/gseapy
  license: MIT
  license_family: MIT
  summary: Gene Set Enrichment Analysis in Python

extra:
  container:
    # matplotlib needs opengl support
    extended-base: true
