{% set version = "1.1.0" %}
{% set sha256 = "14feec65a16d4f71bce0fb6a702a7dd4b61ed07bc1975166c5c8a95be87dc4e6" %}

package:
  name: r-rgbif
  version: '{{ version }}'

source:
  url: https://cran.r-project.org/src/contrib/rgbif_{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-crul >=0.3.4
    - r-data.table
    - r-geoaxe
    - r-ggplot2
    - r-jsonlite >=0.9.16
    - r-magrittr
    - r-oai >=0.2.2
    - r-tibble
    - r-whisker
    - r-wicket >=0.2.0
    - r-xml2
  run:
    - r-base
    - r-crul >=0.3.4
    - r-data.table
    - r-geoaxe
    - r-ggplot2
    - r-jsonlite >=0.9.16
    - r-magrittr
    - r-oai >=0.2.2
    - r-tibble
    - r-whisker
    - r-wicket >=0.2.0
    - r-xml2

test:
  commands:
    - $R -e "library('rgbif')"

about:
  home: https://github.com/ropensci/rgbif
  license: NOASSERTION
  license_family: MIT
  summary: |
    A programmatic interface to the Web Service methods provided by the Global Biodiversity
    Information Facility ('GBIF'; <https://www.gbif.org/developer/summary>). 'GBIF'
    is a database of species occurrence records from sources all over the globe. 'rgbif'
    includes functions for searching for taxonomic names, retrieving information on
    data providers, getting species occurrence records, and getting counts of occurrence
    records.
