{% set version = "1.1.2" %}
{% set sha256 = "c709fc77e5a9e0a97d458034569b09e7a77f49f3f8d3fd0078a10a87a21dc4db" %}

package:
  name: udocker
  version: '{{ version }}'

source:
  url: https://github.com/indigo-dc/udocker/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: true # [not py27 or not linux]

requirements:
  host:
    - python
    - pycurl
  run:
    - python
    - proot
    - simplejson
    - pycurl

about:
  home: https://github.com/indigo-dc/udocker
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Freely available tools for computational molecular biology.
