{% set version = "1.0.3" %}
{% set sha256 = "9e9238602bd1737a788872fda997ba8f58507c043a01f90cb2487284bbd3f307" %}

package:
  name: shovill
  version: '{{ version }}'

source:
  url: https://github.com/tseemann/shovill/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0

requirements:
  run:
    - perl
    - perl-file-spec
    - perl-findbin
    - lighter >=1.1
    - bwa >=0.7.17
    - mash >=2
    - flash >=1.2
    - pilon >=1.22
    - seqtk >=1.3
    - skesa >=2.2
    - megahit >=1.1
    - velvet >=1.2.10
    - samclip >=0.2
    - trimmomatic >=0.36
    - spades >=3.6
    - pigz
    - samtools >=1.8

test:
  commands:
    - shovill --help
    - shovill --version
    - shovill --check

about:
  home: https://github.com/tseemann/shovill
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Microbial assembly pipeline for Illumina paired-end reads
