{% set version = "0.1.1" %}
{% set sha256 = "e78a7a6cf746ffa683779969bb6084ffe39d05af56283c63baf21dae77b02d50" %}

package:
  name: fast5seek
  version: '{{ version }}'

source:
  url: https://github.com/mbhall88/fast5seek/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 1
  entry_points:
    - fast5seek=fast5seek.cli:cli
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [py27]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - ont-fast5-api
    - pysam

test:
  imports:
    - fast5seek
  commands:
    - fast5seek --help

about:
  home: https://github.com/mbhall88/fast5seek
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Get paths for fast5 files contained in BAM, SAM, or fastq.
