{% set version = "1.2.1" %}
{% set sha256 = "3044851561958cda5f7d716de955d826e670e43b0e2efc67be52943be90b18b0" %}

package:
  name: tandem-genotypes
  version: '{{ version }}'

source:
  url: https://github.com/mcfrith/tandem-genotypes/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - r-base

test:
  commands:
    - tandem-genotypes --help
    - tandem-genotypes-join --help
    - tandem-genotypes-plot --help

about:
  home: https://github.com/mcfrith/tandem-genotypes
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Find tandem repeat length changes, from "long" DNA reads aligned to a genome
