{% set version = "0.0.4" %}
{% set sha256 = "98e58d6991a8aca2d404d11c0d745e78fc8ee2ed0253482d49e07b5ed6d0e239" %}

package:
  name: duphold
  version: '{{ version }}'

source:
  url: https://github.com/brentp/duphold/releases/download/v{{ version }}/duphold
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - pcre
    - htslib

test:
  commands:
    - duphold -h

about:
  home: https://github.com/brentp/duphold
  license: MIT
  license_family: MIT
  summary: SV callers like lumpy look at split-reads and pair distances to find structural variants. This tool is a fast way
    to add depth information to those calls.
