{% set version = "0.0.9" %}
{% set sha256 = "6dbca07fce926d4252ce048dc79580068da5b21a7a8776e5a3098276fea72595" %}

package:
  name: duphold
  version: '{{ version }}'

source:
  url: https://github.com/brentp/duphold/releases/download/v{{ version }}/duphold
  sha256: '{{ sha256 }}'

build:
  number: 1
  skip: true  # [osx]

requirements:
  run:
    - pcre
    - htslib

test:
  commands:
    - duphold -h

about:
  home: https://github.com/brentp/duphold
  license: MIT
  license_family: MIT
  summary: SV callers like lumpy look at split-reads and pair distances to find structural variants. This tool is a fast way
    to add depth information to those calls.
