{% set version = "36" %}
{% set sha256 = "6e668caa2568510312ede7a3f75f4880937a2542c2697e44f43d50e04f9ca581" %}

package:
  name: womtool
  version: '{{ version }}'

source:
  url: https://github.com/broadinstitute/cromwell/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 1

requirements:
  host:
    - openjdk >=8
    - sbt
    - scala
  run:
    - openjdk >=8
    - python

test:
  commands:

about:
  home: https://cromwell.readthedocs.io/en/develop/WOMtool/
  license: NOASSERTION
  summary: Command line utilities for interacting with WDL
  dev_url: https://github.com/broadinstitute/cromwell
#    - womtool --help 2>&1 | grep "Performs full validation"

extra:
  identifiers:
    - biotools:womtool
