{% set version = "35" %}
{% set sha256 = "58fd3a8a3756c1a7101948fae50513ce90def5581a974481077678dd28681aae" %}

package:
  name: womtool
  version: '{{ version }}'

source:
  url: https://github.com/broadinstitute/cromwell/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0

requirements:
  host:
    - openjdk >=8
    - sbt
    - scala
  run:
    - openjdk >=8
    - python

test:
  commands:

about:
  home: https://cromwell.readthedocs.io/en/develop/WOMtool/
  license: BSD
  license_family: BSD
  summary: Command line utilities for interacting with WDL
  dev_url: https://github.com/broadinstitute/cromwell
#    - womtool --help 2>&1 | grep "Performs full validation"

extra:
  identifiers:
    - biotools:womtool
