{% set version = "0.7.2" %}
{% set sha256 = "44cbd888a3756b1d116e4bdda43a504243b14c88794080597aa38a89be21166b" %}

package:
  name: r-basejump
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: '{{ version }}'

source:
  url: https://github.com/steinbaugh/basejump/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 1
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base >=3.4.0
    - bioconductor-annotationhub
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-ensembldb
    - bioconductor-genomeinfodb
    - bioconductor-s4vectors
    - r-assertive
    - r-cowplot >=0.9
    - r-dendsort
    - r-matrix.utils >=0.9
    - r-dplyr >=0.7
    - r-pbapply
    - r-devtools
    - r-ggplot2 >=2.2.1
    - r-knitr >=1.2.0
    - r-magrittr >=1.5
    - r-matrix >=1.2
    - r-rio
    - r-sessioninfo
    - r-pheatmap
    - r-rcolorbrewer
    - r-rcurl >=1.95
    - r-readr >=1.1
    - r-readxl >=1.0
    - r-rlang >=0.2
    - r-r.utils
    - r-scales
    - r-stringr >=1.3
    - r-tibble >=1.4
    - r-tidyr >=0.8
    - r-viridis
    - r-yaml
  run:
    - r-base >=3.4.0
    - bioconductor-annotationhub
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-ensembldb
    - bioconductor-genomeinfodb
    - bioconductor-s4vectors
    - r-assertive
    - r-cowplot >=0.9
    - r-dendsort
    - r-matrix.utils >=0.9
    - r-dplyr >=0.7
    - r-pbapply
    - r-devtools
    - r-ggplot2 >=2.2.1
    - r-knitr >=1.2.0
    - r-magrittr >=1.5
    - r-matrix >=1.2
    - r-rio
    - r-sessioninfo
    - r-pheatmap
    - r-rcolorbrewer
    - r-rcurl >=1.95
    - r-readr >=1.1
    - r-readxl >=1.0
    - r-rlang >=0.2
    - r-r.utils
    - r-scales
    - r-stringr >=1.3
    - r-tibble >=1.4
    - r-tidyr >=0.8
    - r-viridis
    - r-yaml

test:
  commands:
    - $R -e "library('basejump')"

about:
  home: https://github.com/steinbaugh/basejump
  license: MIT
  license_family: MIT
  summary: Base functions for bioinformatics and R package development.
