{% set version = "4.0.0" %}
{% set sha256 = "ffde4f75e35e8772764a6432bb81e765226b7a32dce4967fa520dd1b6fd3b11d" %}

package:
  name: elprep
  version: '{{ version }}'

source:
  url: https://github.com/ExaScience/elprep/releases/download/v{{ version }}/elprep-v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 1
  skip: true  # [osx]

test:
  commands:
    - elprep -h

about:
  home: https://github.com/ExaScience/elprep
  license: NOASSERTION
  summary: elPrep is a high-performance tool for preparing .sam/.bam files for variant calling in sequencing pipelines. It
    can be used as a drop-in replacement for SAMtools/Picard/GATK4, and was extensively tested with different pipelines for
    variant analysis with GATK. The key advantage of elPrep is that it only performs a single-pass to process a .sam/.bam
    file, independent of the number of processing steps that need to be applied in a particular pipeline, greatly improving
    runtime performance.
