{% set version = "1.18.0" %}
{% set sha256 = "25e3b39669482c92afa0a4af925feee11b460e94b07f8f24a1ce7ece65035710" %}

package:
  name: vnl
  version: '{{ version }}'

source:
  url: https://github.com/vxl/vxl/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: true  # [py3k or osx]

requirements:
  build:
    - '{{ compiler("c") }}'
    - cmake
  run:

about:
  home: https://sf.net/projects/vxl/
  license: BSD
  license_family: BSD
  summary: A multi-platform collection of C++ software libraries for Computer Vision and Image Understanding.
  dev_url: https://github.com/vxl/vxl
