{% set version = "3.0.24" %}
{% set sha256 = "a89d83208d746dd4a53e273d585ce4d0b4290314b06f1a16a6e4f88cd7259ffa" %}

package:
  name: pyega3
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/p/pyega3/pyega3-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  entry_points:
    - pyega3 = pyega3.pyega3:main
  script: '$PYTHON -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '
  skip: true  # [not py3k]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - requests
    - tqdm

test:
  imports:
    - pyega3
  commands:
    - pyega3 --help

about:
  home: https://github.com/EGA-archive/ega-download-client
  license: Apache-2.0
  license_family: Apache
  summary: EGA python client
  doc_url: https://github.com/EGA-archive/ega-download-client
  dev_url: https://github.com/EGA-archive/ega-download-client
