{% set version = "0.0.9" %}
{% set sha256 = "282c8592aa75e68f5611b902cf4eb774facf6d5738ec3e08db192b7b2bea7806" %}

package:
  name: kodoja
  version: '{{ version }}'

source:
  url: https://github.com/abaizan/kodoja/archive/kodoja-v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 1

requirements:
  run:
    - python
    - kraken
    - kaiju
    - fastqc
    - trimmomatic
    - numpy
    - pandas
    - biopython
    - ncbi-genome-download

test:
  commands:
    - kodoja_search.py --version
    - kodoja_build.py --version
    - kodoja_retrieve.py --version

about:
  home: https://github.com/abaizan/kodoja
  license: MIT
  license_family: MIT
  summary: 'Kodoja: identifying viruses from plant RNA sequencing data'
