{% set version = "35" %}
{% set sha256 = "5ef5afb286a04bf63ab175082597bd9ced5001db35ef34f9a596232aaf2a132c" %}

package:
  name: cromwell
  version: '{{ version }}'

source:
  url: https://github.com/broadinstitute/cromwell/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0

requirements:
  host:
    - openjdk >=8
    - sbt
    - scala
  run:
    - openjdk >=8
    - python
    - findutils

test:
  commands:
    - cromwell --version 2>&1 | grep "cromwell"
    - womtool --help 2>&1 | grep "Usage"

about:
  home: https://github.com/broadinstitute/cromwell
  license: BSD
  license_family: BSD
  summary: A Workflow Management System geared towards scientific workflows described in WDL

extra:
  identifiers:
    - biotools:cromwell
  recipe-maintainers:
    - notestaff
    - tomkinsc
