{% set version = "0.8.9" %}
{% set sha256 = "f4db29aa09748117340623a299b44728b22e85bfde4c6ede716ffd5540fdb537" %}

package:
  name: abricate
  version: '{{ version }}'

source:
  url: https://github.com/tseemann/abricate/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0

requirements:
  host:
    - perl-bioperl >=1.7
    - perl-file-slurp
    - perl-text-csv
    - perl-list-moreutils
    - perl-json
    - perl-lwp-simple
    - blast >=2.7
    - zlib
    - unzip
    - emboss
    - entrez-direct
  run:
    - perl-bioperl >=1.7
    - perl-file-slurp
    - perl-text-csv
    - perl-list-moreutils
    - perl-json
    - perl-lwp-simple
    - blast >=2.7
    - zlib
    - unzip
    - emboss
    - entrez-direct

test:
  commands:
    - abricate --version
    - abricate --list
    - abricate --check

about:
  home: https://github.com/tseemann/abricate
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Mass screening of contigs for antibiotic resistance genes
