{% set version = "0.0.23" %}
{% set sha256 = "c4ca6da98731cdca7395cafe045ed5b82572dc1d3fd343f6a93a11830044939c" %}

package:
  name: starfish
  version: '{{ version }}'

source:
  url: https://github.com/spacetx/starfish/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - click
    - jsonschema
    - matplotlib
    - numpy !=1.13.0
    - pandas >=0.23.4
    - pytest >=3.6.3
    - regional
    - requests
    - scikit-image >=0.14.0
    - scikit-learn
    - scipy
    - seaborn
    - semantic_version
    - tqdm
    - trackpy
    - validators
    - xarray
    - showit ==1.1.4
    - slicedimage ==0.0.6

test:
  imports:
    - starfish

about:
  home: https://github.com/spacetx/starfish
  license: MIT
  license_family: MIT
  summary: standardized analysis pipeline for image-based transcriptomics
