{% set version = "0.4.0" %}
{% set sha256 = "13c715f577034c1d217c7017c4e7be2d11334b52b6c7c9bb888e69c5eae9c185" %}

package:
  name: svtools
  version: '{{ version }}'

source:
  url: https://github.com/hall-lab/svtools/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: true # [not py27 or osx]

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - vcftobedpe -h
  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

about:
  home: https://github.com/hall-lab/svtools
  license: MIT
  license_family: MIT
  summary: Tools for processing and analyzing structural variants.
# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
