{% set version = "1.0.0" %}
{% set sha256 = "a876ddd77692c2f7cbb48e6416699cc7443598c70eec1096d07a0f6fa453e83e" %}

package:
  name: r-rebird
  version: '{{ version }}'

source:
  url: https://cran.r-project.org/src/contrib/rebird_{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-dplyr
    - r-httr >=1.0.0
    - r-jsonlite
  run:
    - r-base
    - r-dplyr
    - r-httr >=1.0.0
    - r-jsonlite

test:
  commands:
    - $R -e "library('rebird')"

about:
  home: https://github.com/ropensci/rebird
  license: NOASSERTION
  license_family: MIT
  summary: |
    A programmatic client for the eBird database, including functions for searching for
    bird observations by geographic location (latitude, longitude), eBird hotspots,
    location identifiers, by notable sightings, by region, and by taxonomic name.
