{% set version = "1.3.1" %}
{% set sha256 = "b0dd1e65600e807abb1c0219fdad13ae47cf35ee6dfc3eb4d22cffa2aff936b6" %}

package:
  name: flowcraft
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/f/flowcraft/flowcraft-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: true # [py27]
  entry_points:
    - flowcraft = flowcraft.flowcraft:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pympler
    - python-dateutil
    - argparse
    - jinja2
    - requests
  run:
    - python
    - pympler
    - python-dateutil
    - argparse
    - jinja2
    - requests
    - nextflow >=0.27

test:
  imports:
    - flowcraft
    - flowcraft.generator
    - flowcraft.generator.components
    - flowcraft.templates
    - flowcraft.templates.flowcraft_utils
  commands:
    - flowcraft --help

about:
  home: https://github.com/assemblerflow/flowcraft
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A Nextflow pipeline assembler for genomics. Pick your modules. Assemble them. Run the pipeline.
  doc_url: http://assemblerflow.readthedocs.io/en/latest/
  dev_url: http://assemblerflow.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - odiogosilva
