{% set version = "0.1.0" %}
{% set sha256 = "6ce970a030f419d2355c6f989e8556aa9be886fde31c9cfa6747ebe60dbfb200" %}

package:
  name: hulk
  version: '{{ version }}'

source:
  url: https://github.com/will-rowe/hulk/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0

requirements:
  build:
    - go
    - mercurial
  run:
    - banner ==0.0.2

test:
  commands:
    - hulk
    - hulk version
    - banner version

about:
  home: https://github.com/will-rowe/hulk
  license: NOASSERTION
  summary: Histosketching Using Little Kmers.
