{% set version = "0.1.2" %}
{% set sha256 = "d27a5e862be461861e10a8c36835749b208d2b1c997e0d81e297525b592f5e64" %}

package:
  name: hulk
  version: '{{ version }}'

source:
  url: https://github.com/will-rowe/hulk/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 2

requirements:
  build:
    - go
    - mercurial

test:
  commands:
    - hulk
    - hulk version

about:
  home: https://github.com/will-rowe/hulk
  license: NOASSERTION
  summary: Histosketching Using Little Kmers.
