{% set version = "0.1.0" %}
{% set sha256 = "99f78d6191bb0fbdd0bd74cefb5d2ce2d1e912e1afd2537560c0ebd0b6e0d4b6" %}

package:
  name: slicedimage
  version: '{{ version }}'

source:
  url: https://github.com/spacetx/slicedimage/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy !=1.13.0
    - diskcache
    - packaging
    - requests
    - scikit-image
    - six

test:
  imports:
    - slicedimage

about:
  home: https://github.com/spacetx/slicedimage
  license: MIT
  license_family: MIT
  summary: sliced imaging data
