{% set version = "1" %}
{% set sha256 = "8df617c78389773a41b452842681e08328d3ac73f646b351407c3a22f61b27e7" %}

package:
  name: slicedimage
  version: '{{ version }}'

source:
  url: https://github.com/spacetx/slicedimage/archive/t{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy !=1.13.0
    - diskcache
    - packaging
    - requests
    - scikit-image
    - six

test:
  imports:
    - slicedimage

about:
  home: https://github.com/spacetx/slicedimage
  license: MIT
  license_family: MIT
  summary: sliced imaging data
